[package]
name = "phoenix-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[features]
default = []
boot-memory-probe = []
el0-probe = []
kernel-map-probe = []
loaded-init-probe = []

[lib]
crate-type = ["rlib"]

[[bin]]
name = "phoenix-kernel"
path = "src/main.rs"
test = false
bench = false

[lints]
workspace = true
